#pragma once

/*
    此文件定义可能被LKVS<>类返回的错误代码
*/

#define LKVS_UNKNOWN_ERROR 1
#define LKVS_CREATE_VS_DIRECTORY_OR_READ_ONLY 2
#define LKVS_CREATE_VS_FILE_EXISTS 3
#define LKVS_CERATE_VS_OUT_OF_HANDLE 4
#define LKVS_CREATE_VS_PATH_NOT_FOUND 5
#define LKVS_CREATE_VS_OUT_OF_SPACE 6
